### ISSUE TITLE
Please, do it available for end users

### ISSUE THREAD

**Issue by Guardian820** [leaningtech/cheerpx-flash#1]
The project is promising, but I haven't found any way to buy an end-user license and because of that I have a few questions: do the creators of this technology, intend to keep trading licenses for companies only? Are there any plans to make the technology available to the general public?

**Comment by alexp-sssup** [comment]
As much as we would love to allow any end user to benefit from CheerpX for Flash, unfortunately that is outside of our control.

CheerpX for Flash includes a commercial build of the Adobe Flash player. We have created the x86-to-WebAssembly virtualization technology (CheerpX) that runs the plugin in modern browsers, but we do not own or licence the plugin itself.

Licensing prices and conditions are in the hands of Harman and Adobe. Our customers are organisations (private and public) in charge of Flash applications that they need to preserve access to. They licence the Adobe Flash Player separately from Harman, and only CheerpX from us.

I am sure that this answer is disappointing to many, but unfortunately this is how things stand with this specific tool.
